// frontend-1/src/shared/mocks/eventsMock.ts
import type { EventFull } from "../../entities/event/index";

export const eventsMock: EventFull[] = [
  {
    id: "evt_001",
    title: "Emma & James Bridal Shower",
    date: "2026-06-30",
    time: "11:00 AM",
    location: "Victorian Tea Room",
    status: "published",
    templateId: "tpl_001",
    templateName: "Bridal Shower Classic",
    previewImage: "/mockphoto/wedding_bg.jpg",
    rsvpCount: 24,
    createdAt: "2026-02-10T09:00:00Z",
    description: "Join us for a beautiful afternoon celebrating Emma and James.",
    hostName: "Sarah Williams",
    guestList: [
      { id: "g1", name: "Alice Johnson", email: "alice@example.com", status: "confirmed", plusOnes: 1 },
      { id: "g2", name: "Bob Smith", email: "bob@example.com", status: "pending" },
      { id: "g3", name: "Carol Davis", email: "carol@example.com", status: "confirmed" },
    ],
    settings: {
      isPrivate: false,
      allowPlusOnes: true,
      maxGuests: 50,
      rsvpDeadline: "2026-06-15",
    },
  },
  {
    id: "evt_002",
    title: "Alex's 30th Birthday",
    date: "2026-04-14",
    time: "7:00 PM",
    location: "Sky Lounge",
    status: "published",
    templateId: "tpl_002",
    templateName: "Floral Birthday",
    previewImage: "/mockphoto/birthday_bg.jpg",
    rsvpCount: 42,
    createdAt: "2026-03-01T14:30:00Z",
    hostName: "Alex Chen",
    guestList: [
      { id: "g4", name: "David Lee", status: "confirmed" },
      { id: "g5", name: "Eva Martinez", email: "eva@example.com", status: "confirmed", plusOnes: 1 },
    ],
    settings: {
      isPrivate: true,
      allowPlusOnes: true,
      maxGuests: 60,
    },
  },
  {
    id: "evt_003",
    title: "Sophia's 5th Birthday",
    date: "2026-05-22",
    time: "2:00 PM",
    location: "Wonderland Playground",
    status: "draft",
    templateId: "tpl_003",
    templateName: "Kids Party Fun",
    previewImage: "/mockphoto/kids_bg.jpg",
    rsvpCount: 0,
    createdAt: "2026-04-01T11:15:00Z",
    hostName: "Maria Gonzalez",
    guestList: [],
    settings: {
      isPrivate: false,
      allowPlusOnes: false,
      maxGuests: 30,
      rsvpDeadline: "2026-05-10",
    },
  },
  {
    id: "evt_004",
    title: "Corporate Gala 2026",
    date: "2026-09-12",
    time: "6:30 PM",
    location: "Grand Plaza Hotel",
    status: "archived",
    templateId: "tpl_001",
    templateName: "Bridal Shower Classic",
    previewImage: "/mockphoto/invite_001.jpg",
    rsvpCount: 118,
    createdAt: "2025-12-05T08:00:00Z",
    hostName: "Jennifer Lee",
    settings: {
      isPrivate: true,
      allowPlusOnes: true,
      maxGuests: 200,
    },
  },
];